name: Trigger on Azure Machine Learning Job merge to main

on: pull_request
jobs:
  train-experiment:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml --resource-group jaein.tak-rg --workspace-name mslearn-mlops
  train-prodcution:
    environment: production
    needs: train-experiment
    if: needs.train-experiment.outcome == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/production-job.yml --resource-group jaein.tak-rg --workspace-name mslearn-mlops

